version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5155:5155"
    environment:
      ASPNETCORE_URLS: http://+:5155
      ASPNETCORE_ENVIRONMENT: Development
